### PR TITLE
FIX: fix mypy checks & development package requirements

### PR DESCRIPTION
**Pull request by mtsokol**

### CODE REVIEW

**Comment by mtsokol** [comment]
Hi @j-ittner,
I'm trying to build env locally (for the current `2.0.x` branch) and it looks to be stuck on SAT solver for dependencies versions (it should end in 2min according to the Internet) - I will try with what they suggest to speed up the solve stage.

**Comment by j-ittner** [comment]
> Hi @j-ittner,
> I'm trying to build env locally (for the current `2.0.x` branch) and it looks to be stuck on SAT solver for dependencies versions (it should end in 2min according to the Internet) - I will try with what they suggest to speed up the solve stage.

Thanks @mtsokol - any suggestions you found that you can share here (other than pinning versions more specifically)?

**Comment by mtsokol** [comment]
> > Hi @j-ittner,
> > I'm trying to build env locally (for the current `2.0.x` branch) and it looks to be stuck on SAT solver for dependencies versions (it should end in 2min according to the Internet) - I will try with what they suggest to speed up the solve stage.
> 
> Thanks @mtsokol - any suggestions you found that you can share here (other than pinning versions more specifically)?

Still experimenting locally, but nothing specific except for setting exact dependencies versions with `==`.

[EDIT] I will check how it behaves with all deps pinned exactly.

**Comment by mtsokol** [comment]
It looks that pinning dependencies to minor versions worked - now the testing phase takes 9min (5min conda & solving environment and 4min actual tests).

Also as now pinned version of `scikit-learn` is `1.2.0` there's no `load_boston` method available within the API. Therefore I moved to `california_housing` dataset suggested as a replacement. 

Now the pipeline finally completed all green.

**Review by j-ittner — APPROVED** [review]
looks good, thanks!

**Comment by mtsokol** [comment]
> looks good, thanks!

Hi @j-ittner, thanks! Just one more question: I see that as Facet is provided via `conda` and `pip` we need to maintain `environment.yml` and `project.toml` as well (which basically repeats dependencies' versions). Should we also reflect these version changes for dependencies in `project.toml`?   

(I see the latest `2.0.x` branch run (https://dev.azure.com/gamma-facet/facet/_build/results?buildId=6101&view=logs&j=09c2097a-0b11-57be-b64a-b3816f33e8dc&t=71aad4fa-69fa-5035-9ac5-401f175fe9ed&l=73146) failed for tox minimum dependencies, on precision error, so I would assume we need to increase lower bound version constraint on some dependency.

**Pull request merged**
